version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGO_DATABASE: portfolio-data
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: data-client
      PORT: 3002
